services:
  # Player role repository
  ghostst_core.repository.game.player_role:
    class: GhostSt\CoreBundle\Repository\Game\PlayerRoleRepository
    arguments:
      - "@doctrine_mongodb"

  # Setting repository
  ghostst_core.repository.tools.setting:
    class: GhostSt\CoreBundle\Repository\Tools\SettingRepository
    arguments:
      - "@doctrine_mongodb"

  # User rating repository
  ghostst_core.repository.rating.user_rating:
    class: GhostSt\CoreBundle\Repository\Rating\UserRatingRepository
    arguments:
      - "@doctrine_mongodb"
