imports:
    - { resource: admins.yml }
    - { resource: forms.yml }
    - { resource: parameters.yml }
    - { resource: repositories.yml }
    - { resource: validators.yml }

services:
  # Game service
  ghostst_core.service.game.game:
    class: GhostSt\CoreBundle\Service\Game\GameService
    arguments:
      - "@ghostst_core.repository.game"

  # Game result resolver
  ghostst_core.service.game.game_result_resolver:
    class: GhostSt\CoreBundle\Service\Game\GameResultResolver
    arguments:
      - "@ghostst_core.service.role.player_role"

  # Player role service
  ghostst_core.service.role.player_role:
    class: GhostSt\CoreBundle\Service\Role\PlayerRoleService
    arguments:
      - "@ghostst_core.service.tools.setting"
      - "@ghostst_core.repository.game.player_role"

  # Setting service
  ghostst_core.service.tools.setting:
    class: GhostSt\CoreBundle\Service\Tools\SettingService
    arguments:
      - "@ghostst_core.repository.tools.setting"
      - "%settings%"

  # Rating calculator
  ghostst_core.service.rating.calculator:
    class: GhostSt\CoreBundle\Service\Rating\RatingCalculator
    arguments:
      - "@ghostst_core.service.rating.strategy.aggregator"

  # Rating service
  ghostst_core.service.rating.rating:
    class: GhostSt\CoreBundle\Service\Rating\RatingService
    arguments:
      - "@ghostst_core.service.rating.calculator"
      - "@ghostst_core.repository.rating.user_rating"

  # Aggregator strategy service
  ghostst_core.service.rating.strategy.aggregator:
    class: GhostSt\CoreBundle\Service\Rating\Strategy\AggregatorStrategy

  # Civilian strategy service
  ghostst_core.service.rating.strategy.civilian:
    class: GhostSt\CoreBundle\Service\Rating\Strategy\CivilianStrategy
    arguments:
      - "@ghostst_core.service.role.player_role"
    tags:
      - { name: 'rating.strategy' }

  # Civilian strategy service
  ghostst_core.service.rating.strategy.mafia:
    class: GhostSt\CoreBundle\Service\Rating\Strategy\MafiaStrategy
    arguments:
      - "@ghostst_core.service.role.player_role"
    tags:
      - { name: 'rating.strategy' }

  # Civilian strategy service
  ghostst_core.service.rating.strategy.best_move:
    class: GhostSt\CoreBundle\Service\Rating\Strategy\BestMoveStrategy
    arguments:
      - "@ghostst_core.service.role.player_role"
    tags:
      - { name: 'rating.strategy' }

  # AMQP manager
  ghostst_core.service.amqp_manager:
    class: GhostSt\CoreBundle\Service\AMQPManager
    arguments:
      - "%amqp_host%"
      - "%amqp_port%"
      - "%amqp_user%"
      - "%amqp_password%"

  # General player statistic
  ghostst_core.service.statistic.general_player:
      class: GhostSt\CoreBundle\Service\Statistic\GeneralPlayersStatistic
      arguments:
          - "@ghostst_core.service.game.game"
          - "@ghostst_core.service.rating.rating"
          - "@ghostst_core.service.statistic.calculator"

  # Statistic calculator
  ghostst_core.service.statistic.calculator:
      class: GhostSt\CoreBundle\Service\Statistic\StatisticCalculator
      arguments:
        - "@ghostst_core.service.game.game_result_resolver"
        - "@ghostst_core.service.role.player_role"
