services:
  # Position validator
  ghostst_core.validator.constraint.position:
    class: GhostSt\CoreBundle\Validator\Constraints\PositionValidator
    arguments:
      - "@translator"
    tags:
      - { name: validator.constraint_validator }

  # Best move guess validator
  ghostst_core.validator.constraint.best_move_guess:
    class: GhostSt\CoreBundle\Validator\Constraints\BestMoveGuessValidator
    arguments:
      - "@translator"
    tags:
      - { name: validator.constraint_validator }

  # Player validator
  ghostst_core.validator.constraint.player:
    class: GhostSt\CoreBundle\Validator\Constraints\PlayerValidator
    arguments:
      - "@translator"
    tags:
      - { name: validator.constraint_validator }

  # Role validator
  ghostst_core.validator.constraint.role:
    class: GhostSt\CoreBundle\Validator\Constraints\RoleValidator
    arguments:
      - "@translator"
    tags:
      - { name: validator.constraint_validator }
