# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    GhostSt:
                        password: $2y$12$i.l7S2bDB1X4YEP7chvI.etnnZNbLm0a/6Vi.8e2drA0RYotK8EFy
                        roles: 'ROLE_ADMIN'
                    sasha_zd:
                        password: $2y$12$BOsmRcxMv2w1AlFS.Te0..8q.uPxGtliZmG3thti8EQx7s1huZuBe
                        roles: 'ROLE_ADMIN'

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                provider: in_memory
                default_target_path: /admin/dashboard
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
