<?php

namespace GhostSt\CoreBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 * @Target({"PROPERTY", "METHOD", "ANNOTATION"})
 */
class Role extends Constraint
{
    public function validatedBy()
    {
        return RoleValidator::class; // TODO: Change the autogenerated stub
    }
}