services:
# Admin
  ghostst_core.admin.user:
    class: GhostSt\CoreBundle\Admin\UserAdmin
    arguments: [~, GhostSt\CoreBundle\Document\User, ~]
    tags:
      - { name: sonata.admin, manager_type: doctrine_mongodb, label: Игроки }

  ghostst_core.admin.game:
    class: GhostSt\CoreBundle\Admin\GameAdmin
    arguments: [~, GhostSt\CoreBundle\Document\Game, GhostStCoreBundle:Admin/Game]
    tags:
      - { name: sonata.admin, manager_type: doctrine_mongodb, label: Игры }
# Services

# Form types
  ghostst_core.form.type.player:
    class: GhostSt\CoreBundle\Form\Type\PlayerType
    arguments:
    tags:
     - { name: form.type }

# Validators
  ghostst_core.validator.constraint.position:
    class: GhostSt\CoreBundle\Validator\Constraints\PositionValidator
    arguments:
      - "@translator"
    tags:
      - { name: validator.constraint_validator }

  ghostst_core.validator.constraint.best_move_guess:
    class: GhostSt\CoreBundle\Validator\Constraints\BestMoveGuessValidator
    arguments:
      - "@translator"
    tags:
      - { name: validator.constraint_validator }

  ghostst_core.validator.constraint.player:
    class: GhostSt\CoreBundle\Validator\Constraints\PlayerValidator
    arguments:
      - "@translator"
    tags:
      - { name: validator.constraint_validator }

  ghostst_core.validator.constraint.role:
    class: GhostSt\CoreBundle\Validator\Constraints\RoleValidator
    arguments:
      - "@translator"
    tags:
      - { name: validator.constraint_validator }
